presubmits:
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: pull-cluster-api-provider-digitalocean-build
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200131-0997840-master
        command:
        - make
        args:
        - manager
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: build
  - name: pull-cluster-api-provider-digitalocean-test
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200131-0997840-master
        command:
        - make
        args:
        - test
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: test
  - name: pull-cluster-api-provider-digitalocean-verify
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200131-0997840-master
        command:
        - make
        args:
        - verify
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: verify
  - name: pull-cluster-api-provider-digitalocean-lint
    always_run: true
    decorate: true
    path_alias: sigs.k8s.io/cluster-api-provider-digitalocean
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200131-0997840-master
        command:
        - make
        args:
        - lint
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: lint
