postsubmits:
  kubernetes-sigs/cluster-api-provider-digitalocean:
  - name: post-cluster-api-provider-digitalocean-e2e
    path_alias: "sigs.k8s.io/cluster-api-provider-digitalocean"
    decorate: true
    decoration_config:
      timeout: 5h
    max_concurrency: 1
    labels:
      preset-dind-enabled: "true"
      preset-kind-volume-mounts: "true"
      preset-do-credential: "true"
    spec:
      containers:
      - image: gcr.io/k8s-testimages/kubekins-e2e:v20200929-82b41a1-master
        command:
          - "runner.sh"
          - "./scripts/ci-e2e.sh"
        securityContext:
          privileged: true
        resources:
          requests:
            cpu: 1
            memory: "4Gi"
    annotations:
      testgrid-dashboards: sig-cluster-lifecycle-cluster-api-provider-digitalocean
      testgrid-tab-name: post-e2e
